### ISSUE TITLE
Defaults must be set on the server side for web apps

### ISSUE THREAD

**Issue by arkilic** [NSLS-II/analysisstore#7]
@hhslepicka and potentially @licode for your guis and web apps that doesn't necessarily use the python api

**Comment by hhslepicka** [comment]
:+1:

**Comment by licode** [comment]
thanks. we should talk more on this.

**Comment by arkilic** [comment]
@licode, sure lets get together this week

**Comment by arkilic** [comment]
part of https://github.com/NSLS-II/analysisstore/pull/8

**Comment by arkilic** [comment]
Closed by #8
